### ISSUE TITLE
Issue with lumi dataset transform

### ISSUE THREAD

**Issue by singhanj13** [tryolabs/luminoth#127]
When I run: lumi dataset transform --type voc --data-dir ./dataset/pascalvoc/ --output-dir ./dataset/voc/tf/
I dont get any error, but the command doesn't run successfully either.

**Comment by IanTayler** [comment]
Hi @singhanj13! Thanks for the heads up!

You have to specify which splits you want to transform with multiple occurrences of the `--split` option. Like this:
`lumi dataset transform --type voc --data-dir ./dataset/pascalvoc/ --output-dir ./dataset/voc/tf/ --split train --split val --split test`.

It makes sense to me that we should add a warning when no `--split` flag is passed, so thanks for the input! I already made a PR with those changes.

**Comment by singhanj13** [comment]
Also I am getting the following error when I run the above command:
ERROR:tensorflow:Data is missing. Removing record file.

I have formatted my dataset to be in the pascalvoc format (3 folders: Annotations, JPEGImages and ImageSets). Could you please tell me what change I should make to resolve this error?
Thanks!
<img width="590" alt="screen shot 2017-11-22 at 10 27 28 pm" src="https://user-images.githubusercontent.com/10827200/33139831-6562d08e-cfd4-11e7-9be1-bd4c4a1159dd.png">

**Comment by singhanj13** [comment]
Resolved it! My images had  .JPEG extension as opposed to .jpg because of which my files were not readable by pascalvoc.py

**Comment by singhanj13** [comment]
Thanks for the quick reply!
