### ISSUE TITLE
Error while training on pascalvoc dataset

### ISSUE THREAD

**Issue by singhanj13** [tryolabs/luminoth#130]
While training, I faced the following error with the first image itself. Can you please help me resolve this?

<img width="590" alt="screen shot 2017-11-22 at 11 02 00 pm" src="https://user-images.githubusercontent.com/10827200/33141515-6637ae30-cfd9-11e7-956b-ea718a608807.png">

**Comment by IanTayler** [comment]
Nice catch! Thanks!

Should be fixed on master now. If you want to fix it without upgrading to the latest master, you can cd to `/home/ansingh8/miniconda2/lib/python2.7/site-packages/luminoth` and run `git init`.
