### ISSUE TITLE
Convert and use JPG / PNG files

### ISSUE THREAD

**Issue by Fearify** [tryolabs/luminoth#138]
I have a number of folders containing JPG and PNG images, how can I import these files and use them with luminoth? We have tried to convert these to a tfrecords format but with our current implementation we get a lot of errors during training. Do you have any sample code for how to do this properly?

**Comment by IanTayler** [comment]
Hi, @Fearify !

Currently our implementation of object detection datasets assume images saved to tfrecors to be encoded in JPEG in [this line](https://github.com/tryolabs/luminoth/blob/master/luminoth/datasets/object_detection_dataset.py#L99). That's easily fixable, so I'll get onto it.

The abstract class used for defining object detection readers is defined at [object_detection_reader.py](https://github.com/tryolabs/luminoth/blob/master/luminoth/tools/dataset/readers/object_detection/object_detection_reader.py). If you want to see a few examples, check out the implementations over at [luminoth/tools/dataset/readers/object_detection](https://github.com/tryolabs/luminoth/tree/master/luminoth/tools/dataset/readers/object_detection), of which `flat_reader.py` and `csv_reader.py` are probably the simplest.

Some of the readers assume your images have a specific extension (e.g. the [pascalvoc reader](https://github.com/tryolabs/luminoth/blob/master/luminoth/tools/dataset/readers/object_detection/pascalvoc.py#L105) assumes your images have a `.jpg` extension). On the other hand, [flat_reader.py](https://github.com/tryolabs/luminoth/blob/master/luminoth/tools/dataset/readers/object_detection/flat_reader.py#L160) shows how to make your reader extension-agnostic.

If you have any other questions, don't hesitate to ask!

**Comment by IanTayler** [comment]
Hi, @Fearify ! We now support PNGs, so I'm closing this issue. If your problem still hasn't been fixed with the latest code at master, then feel free to re-open it with an explanation of what issues you are encountering.
