### ISSUE TITLE
Why I always can not generate the tfrecords using imagenet

### ISSUE THREAD

**Issue by Phillylyu** [tryolabs/luminoth#140]
I am working on Windows platform. 
I create the folder dataset/imagenet, and put one class pic in the folder.
they are n01531178_14.JPEG...... almost 100 pics.
using the command lumi dataset transform imagenet ....
But always I can not find the tfrecord in tf folder

**Comment by IanTayler** [comment]
Hi, @Phillylyu !

Try adding the `--split` option like I mentioned at [this other issue](https://github.com/tryolabs/luminoth/issues/127#issuecomment-346375053) and tell me if that works!

**Comment by Phillylyu** [comment]
@IanTayler yes,u are right.  I add the --split option, now the tfrecords is generated ok.
thx.
