### ISSUE TITLE
Idea/question: Single-instance localisation

### ISSUE THREAD

**Issue by pwichmann** [tryolabs/luminoth#143]
This looks very promising! Thank you.

Would luminoth be suitable for the following single-instance localisation problem?

```
You have two images: A and B
Please check if there is something in image A that looks similar to image B. 
If you find something that looks like it, tell me how similar it is and where it is.
```

I am looking for a smarter solution to a "template matching" problem where images can be rotated, scaled up or down, or even slightly different to the template.

**Comment by vierja** [comment]
Hi @pwichmann!

I'm not sure it would be suitable for Luminoth at this stage, do you have links to papers/articles describing possible models that solve this problem? We would love to take a closer look at how it would be implemented.

Thanks!
