### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by ChromoBacterium** [tryolabs/luminoth#146]
Hi there! 
I was wondering if Luminoth is being tested on Windows yet. I want to install it on windows so I can train my Tensorflow models. I wanted to install it on Ubuntu, but I don't know if my parents would allow it. I know Luminoth isn't Windows supported yet, I just want to know if it will be and if it is being tested.
Thanks in advance,
Ayaz Amin

**Comment by vierja** [comment]
Hi @ChromoBacterium,
Unfortunately we don't have any experience running TensorFlow on Windows and we currently don't have any Windows computers to test on.
You are welcome to try to install it on your Windows machine and we'll be happy to help you (or at least try to) in any way we can.
Thanks for your interest in Luminoth! 😄
