### ISSUE TITLE
InvalidArgumentError with dataset from CSVReader

### ISSUE THREAD

**Issue by clicit** [tryolabs/luminoth#149]
I successfully created a custom dataset with the CSVReader. But when I want to use it for local training with default FRCNN config, I get the following error: 

```
Traceback (most recent call last):
  File "c:\path\to\python\python36\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "c:\path\to\python36\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "c:\path\to\python\python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: fasterrcnn/rpn/rpn_bbox_target/histogram
         [[Node: fasterrcnn/rpn/rpn_bbox_target/histogram = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fasterrcnn/rpn/rpn_bbox_target/histogram/tag, fasterrcnn/rpn/anchor_target/ScatterNd)]]
```

The images all have a resolution of 640x480 and are labeled with class "car".
I tried the suggestions from issue #133 , without success.

Any ideas?
Thanks!

**Comment by vierja** [comment]
Hi @clicit,

Does it fail right away or after a while?

**Comment by clicit** [comment]
Hi Javier,
it fails after some minutes before any images are processed.
Thanks

Am 16. Januar 2018 17:20:16 MEZ schrieb Javier Rey <notifications@github.com>:
>Hi @clicit,
>
>Does it fail right away or after a while?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tryolabs/luminoth/issues/149#issuecomment-358016980

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
