### ISSUE TITLE
Is there a full documented toturial

### ISSUE THREAD

**Issue by Chunde** [tryolabs/luminoth#158]
I try to use luminoth to detect objects,  the image displayed in this Repro is pretty cool

https://user-images.githubusercontent.com/1590959/36434494-e509be42-163d-11e8-99c1-d1aa728929ec.jpg

But there is not detailed example showing how to get this, which make the code very hard to use and I hope someone would write a full toturial so we can get started. thanks!

**Comment by nagitsu** [comment]
A tutorial is coming very shortly, along with pre-trained checkpoints for easy usage (two-three weeks timeframe). Please stay tuned! :smile:

**Comment by nagitsu** [comment]
@Chunde we just pushed our new checkpoints functionality to `master`. You should be able to reproduce the image results by issuing the following command (assuming you have `master` installed):

```
$ lumi server web --checkpoint=accurate
```

This will prompt you to download the checkpoint and will start a server in http://127.0.0.1:5000 for you to play with. Let me know if you run into any issues!

**Comment by Chunde** [comment]
@nagitsu Thanks a lot! Cheers~
