### ISSUE TITLE
Do you have a plan to extend the current faster-rcnn to FPN-based?

### ISSUE THREAD

**Issue by Kongsea** [tryolabs/luminoth#165]
FPN can use multiscale features and it improves the accuracy much more than the original faster-rcnn.
So do you have a plan to implement a FPN-based faster-rcnn?
Thank you.

**Comment by nagitsu** [comment]
It's in the roadmap, yes, and we even have a partial implementation of RetinaNet's FPN in the branch [`retinanet`](https://github.com/tryolabs/luminoth/tree/retinanet). However, our priorities right now are on improving the documentation and library ergonomics before working on additional model changes, so we won't be working on it for the time being.

**Comment by Kongsea** [comment]
Look forward to it and thank you for your awesome work.
