### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by Phillylyu** [tryolabs/luminoth#169]
I am using the latest source code to run the trainning . 
I suffered the following error:
  File "/root/luminoth/luminoth/models/fasterrcnn/rcnn.py", line 221, in _build
    cls_prob = tf.nn.softmax(cls_score, axis=1)
TypeError: softmax() got an unexpected keyword argument 'axis'

My Environment: TF 1.3+Ubutu14.04 +Anaconda 3+python 3.5

**Comment by nagitsu** [comment]
Try using the latest Tensorflow version, as the `dim` argument of `tf.nn.softmax` was deprecated and changed for `axis`.

We'll update the dependencies accordingly, as we seem to have missed it.
