### ISSUE TITLE
Adding examples for using Python API

### ISSUE THREAD

**Issue by chricke** [tryolabs/luminoth#175]
There is a hint "Use the Python API to call Luminoth models within Python." in the docs but i did not found any example how to use a self trained model / checkpoint in my python code.

Could you please add this?

**Comment by chricke** [comment]
ok, so if i understand the code correctly i can give the checkpoint for my self trained network as parameter to the the predict function, right?

I will give it a try, thanks!

**Comment by joaqo** [comment]
Yeah, when you create your `network` object you pass a config file to the `PredictorNetwork` class, which then loads the checkpoint defined in that config. Then its just a matter of calling `network.predict_image(image)`.

We have some helper methods for helping with loading the config file, which you can look at in the `predict.py` file I linked to earlier.

**Comment by chricke** [comment]
Just as a hint for others:
you also have to use get_checkpoint_config to get the config of your checkpoint, so the whole example would look like this:

```
from PIL import Image

from luminoth.tools.checkpoint import get_checkpoint_config
from luminoth.utils.predicting import PredictorNetwork

config = get_checkpoint_config(checkpoint)
network = PredictorNetwork(config)
image = Image.open(f).convert('RGB')
objects = network.predict_image(image)
```

**Comment by dekked** [comment]
We now have an official example [in the tutorial](https://luminoth.readthedocs.io/en/latest/tutorial/07-using-luminoth-from-python.html) :)
