### ISSUE TITLE
Luminoth install problem

### ISSUE THREAD

**Issue by ctruell** [tryolabs/luminoth#182]
Hi I am trying to install luminoth, but every time I check to see if it is installed using the `lumi --help` command I get prompted with this:
`Clares-MacBook-Pro:~ clare$ lumi --help
-bash: /Library/Frameworks/Python.framework/Versions/2.7/bin/lumi: No such file or directory`
I tried uninstalling and reinstalling multiple times and tried following the path listed here but I have no Frameworks folder in my Library folder.
Do you know what is going wrong?

**Comment by dekked** [comment]
Please let us know if this is happening with latest `master`.
