### ISSUE TITLE
Installation problem. Ubuntu

### ISSUE THREAD

**Issue by Oper18** [tryolabs/luminoth#194]
When install luminoth from source I have an error:

telebot 0.0.3 has requirement requests==2.7.0, but you'll have requests 
2.19.1 which is incompatible.
Installing collected packages: pyasn1, pyasn1-modules, cachetools, 
google-auth, httplib2, google-auth-httplib2, google-api-python-client, 
setuptools, protobuf, googleapis-common-protos, idna, urllib3, chardet, 
requests, google-api-core, google-cloud-core, google-resumable-media, 
google-cloud-storage, itsdangerous, Werkzeug, Jinja2, Flask, scipy, 
sk-video, oauth2client, grpcio, html5lib, bleach, markdown, tensorboard, 
gast, astor, termcolor, tensorflow, luminoth
   Found existing installation: pyasn1 0.1.9
     Uninstalling pyasn1-0.1.9:
       Successfully uninstalled pyasn1-0.1.9
   Found existing installation: httplib2 0.9.1
Cannot uninstall 'httplib2'. It is a distutils installed project and 
thus we cannot accurately determine which files belong to it which would 
lead to only a partial uninstall.

When I install it by pip I have an error:

Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", 
line 11, in <module>
         from setuptools.extern.six.moves import filterfalse, map
       File 
"/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, 
in <module>
         from pkg_resources.extern import VendorImporter
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2927, in <module>
         @_call_aside
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2913, in _call_aside
         f(*args, **kwargs)
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2952, in _initialize_master_working_set
         add_activation_listener(lambda dist: dist.activate())
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 956, in subscribe
         callback(dist)
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2952, in <lambda>
         add_activation_listener(lambda dist: dist.activate())
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2515, in activate
         declare_namespace(pkg)
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2097, in declare_namespace
         _handle_ns(packageName, path_item)
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2047, in _handle_ns
         _rebuild_mod_path(path, packageName, module)
       File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", 
line 2066, in _rebuild_mod_path
         orig_path.sort(key=position_in_sys_path)
     AttributeError: '_NamespacePath' object has no attribute 'sort'

**Comment by nagitsu** [comment]
We don't require a specific `requests` version, as we only use the basic API. If it's giving you problems, you could first install `telebot` and then Luminoth (or force the `requests` version you want with `pip install requests==2.7.0`).

**Comment by dekked** [comment]
In latest `master`, we require any version of `requests`. Before, this was installed as a dependency for the Google Cloud integration. Now, as the Google Cloud integration dependencies are optional, we have ensured `requests` is installed in setup.py.
