### ISSUE TITLE
When I finish training using luminoth, How can I freeze the model?

### ISSUE THREAD

**Issue by RobotIntelligence** [tryolabs/luminoth#196]
Which node should I use as output node?
Thanks

**Comment by dekked** [comment]
Hi @RobotIntelligence, and sorry for the delay.

Currently, Luminoth does not support the freezing of the checkpoint to serve via TF Serving. This would be the best way to deploy a model in production.

This is a planned feature with high priority in our list.

If you have any more questions, feel free to create more issues here :muscle:
