### ISSUE TITLE
Error evaluating model in Google Cloud

### ISSUE THREAD

**Issue by joaquinfernandez131** [tryolabs/luminoth#198]
When submitting a job for evaluate a model I do this way: 

![image](https://user-images.githubusercontent.com/1659353/43229490-4bba3e24-903b-11e8-9388-e1a61d9afcbf.png)

Then in GCloud fails because it adds an argument `--job-dir` that function `eval` from `eval.py` doesn't support.

![image](https://user-images.githubusercontent.com/1659353/43229459-33baf87c-903b-11e8-9fa8-f0f39ffd1b60.png)

![image](https://user-images.githubusercontent.com/1659353/43229567-8df12d5c-903b-11e8-9efa-51d28d4afba1.png)

**Comment by dekked** [comment]
Hello @joaquinfernandez131!

Can you try it out with [this PR](https://github.com/tryolabs/luminoth/pull/202)? It should fix the issue.

Beware that the commands changed a bit, but see the examples in the documentation :)
