### ISSUE TITLE
How can I convert a VOC style data base into a COCO style database

### ISSUE THREAD

**Issue by EthanReid** [tryolabs/luminoth#203]

**Comment by dekked** [comment]
Hello Ethan!

Can you expand? Are you trying to get those datasets in a format that can be ingested by Luminoth? For that, you must transform the dataset into TFrecords format. You can read [this page in the docs](https://luminoth.readthedocs.io/en/latest/usage/dataset.html) for how to do that.

**Comment by EthanReid** [comment]
Thanks for the reply,

I ran this
`lumi dataset transform \
        --type pascal \
        --data-dir DataOut \
        --output-dir datasets/pascal/tf/ \
        --split train --split val`

and I get this 
` File "/home/parallels/.virtualenvs/cv/lib/python3.5/site-packages/luminoth/tools/dataset/readers/object_detection/pascalvoc.py", line 46, in _validate_structure
    raise InvalidDataDirectory('Labels path is missing')
luminoth.tools.dataset.readers.base_reader.InvalidDataDirectory: Labels path is missing
`

I am using a custom data set, but it should be in the format of Pascal Voc. Do you know what is going on?

**Comment by dekked** [comment]
This error is when it cannot find `ImageSets/Main` folder. Are you sure your dataset is in the exact same format as expected from Pascal VOC?:
```
ImageSets/Main
JPEGImages
Annotations
```

**Comment by EthanReid** [comment]
Sorry,
I'm still pretty new to this

I'm not 100% sure. My database goes images/image1.jpg 

Can I use what I have?

<img width="463" alt="screen shot 2018-08-17 at 5 11 08 pm" src="https://user-images.githubusercontent.com/7475910/44293523-b8647c80-a240-11e8-8c19-67dcb1ee4298.png">
<img width="463" alt="screen shot 2018-08-17 at 5 09 30 pm" src="https://user-images.githubusercontent.com/7475910/44293528-bd293080-a240-11e8-936a-0310c1482a3a.png">
<img width="347" alt="screen shot 2018-08-17 at 5 09 18 pm" src="https://user-images.githubusercontent.com/7475910/44293533-c0bcb780-a240-11e8-9b84-949f278cbbda.png">

**Comment by dekked** [comment]
Hi @EthanReid!

There seems to be no dataset reader in Luminoth that supports this format.

For reading a dataset, the folder structure and format of the annotation must be supported by Luminoth (Pascal VOC, COCO, etc).

Where did you get this dataset from? Is it open and public? If so, we could take a look and try to build a reader that works for this.
