### ISSUE TITLE
How to resume training with updated tfrecords

### ISSUE THREAD

**Issue by mauricio-meli** [tryolabs/luminoth#206]
I have a trained model with some custom classes but I need to fine tune it adding new tagged examples to the training set.
I've already updated the tfrecords but I can't resume the training job after it is canceled and I also can´t start a new training job with the old job_id.

All I could do is starting a new training job from zero with the updated tfrecords but it trains from the resnet checkpoint instead of my pretrained checkpoint. 

So, is there a way to resume a training job after modifying the train.tfrecords?

**Comment by dekked** [comment]
Just added this in #207 (now merged), try it out and let us know!
