### ISSUE TITLE
Evaluation Problem

### ISSUE THREAD

**Issue by zerok01** [tryolabs/luminoth#212]
Hello, I trained my own dataset in the VOC 2007 format. Then I use the Eval function to evaluate the model. But I get an error like this. What is this solution?
![imageedit_2_7634747698](https://user-images.githubusercontent.com/34706028/44877605-27b08680-acad-11e8-990b-97daed48ccb1.png)

command I use when making the evaluation : lumi eval -c last_config.yaml

Please help, How can i evaluate my model (AP, Accuracy...etc)?

**Comment by dekked** [comment]
Can you show us the content of the `<job_dir>/<run_name>` folder?

Thanks!

**Comment by zerok01** [comment]
Folder content:
![1](https://user-images.githubusercontent.com/34706028/44903618-b0630d00-ad15-11e8-8314-d72d64e329eb.png)

**Comment by nagitsu** [comment]
The message you're seeing is not an error, it's saying that it already evaluated the checkpoint at step `1005072`. Once it finishes evaluation, the `lumi eval` script will keep waiting until a new checkpoint appears in the folder, unless you specify the `--no-watch` option.

The mAP value should have been printed before all those messages, and should have been logged to Tensorboard under the `metrics` section.
