### ISSUE TITLE
Error: No such command "transform "

### ISSUE THREAD

**Issue by litelo** [tryolabs/luminoth#219]
While running the command "lumi dataset transform  -- type csv - - data-dir data/ - - output-dir tfdata/  -- split train - - split val  -- only-classes=table"
I got the this "Error: No such command "transform " how to resolve please help

**Comment by jsasmitha** [comment]
I see both the commands are same, can you highlight the difference

**Comment by RameshOswal** [comment]
for some reason it was not working for me also. could you try this way - not sure why this works and other not.

```
lumi dataset transform \
		--type csv \
		--data-dir data/ \
		--output-dir tfdata/ \
		--split train --split val \
		--only-classes=table
```

**Comment by dekked** [comment]
@litelo what platform are you using Luminoth on?

**Comment by dekked** [comment]
The command you pasted has [unicode spaces]():

```
Python 3.6.7rc1 (default, Sep 27 2018, 09:51:25) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: a = 'lumi dataset transform  -- type csv - - data-dir data/ - - output-dir tfdata/  -- split tra
   ...: in - - split val  -- only-classes=table'                                                        

In [2]: a                                                                                               
Out[2]: 'lumi dataset transform\u200a --\u200atype csv -\u200a-\u200adata-dir data/ -\u200a-\u200aoutput-dir tfdata/\u200a --\u200asplit train -\u200a-\u200asplit val\u200a --\u200aonly-classes=table'
```

Please only use regular spaces, as:
```
lumi dataset transform --type csv --data-dir data/ - output-dir tfdata/ --split train --split val --only-classes=table
```

**Comment by himani88** [comment]
Use the below command:

lumi dataset transform --type csv --data-dir Data/ --output-dir Data/tfdata/ --split train --split val --only-classes=table 
it worked for me
