### ISSUE TITLE
[VOCPASCAL] Truncated, difficult, pose why not use them?

### ISSUE THREAD

**Issue by jsdussanc** [tryolabs/luminoth#220]
I know that in other formats it is not supported, but in VOC yes the attributes of truncated, difficult, pose, I understand that the pose may not be very easy to parameterize, but the other two do not.

Do you think that these parameters can help a better train?

**Comment by dekked** [comment]
Pose is another task altogether, different to object detection, where a different model than Faster R-CNN is required. This task is normally called **pose estimation**, and Luminoth does not yet support it.

As of the other attributes, they have always been ignored in the official [Pascal VOC challenge](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/index.html):
>  The difficult field being set to 1 indicates that the object has been annotated as ``difficult'', for example an object which is clearly visible but difficult to recognize without substantial use of context. **Currently the evaluation ignores such objects**, contributing nothing to the precision/recall curve.

More than help during training, these likely add noise that confuses the algorithms that currently exist.

**Comment by jsdussanc** [comment]
Thanks for answering
