### ISSUE TITLE
Checkpoint import failing on Python 3.5

### ISSUE THREAD

**Issue by samkit-jain** [tryolabs/luminoth#222]
Output when running `lumi checkpoint import file.tar`

![screenshot from 2018-10-22 16 37 34](https://user-images.githubusercontent.com/15127115/47289809-184d1a00-d61a-11e8-9d63-09195da444d1.png)

Works fine with Python 3.6

**Comment by dekked** [comment]
Thanks for the report @samkit-jain, this is definitely the case. It should be fixed now.
