### ISSUE TITLE
Use luminoth to train a model on Microsoft Azure

### ISSUE THREAD

**Issue by abhi1489** [tryolabs/luminoth#225]
Luminoth Documentation describes how we can train a model on google cloud. Is it supported on the Microsoft Azure platform as well?

**Comment by dekked** [comment]
Hi @abhi1489!

We currently only support Google Cloud ML Engine.

[Azure Machine Learning Service](https://docs.microsoft.com/en-us/azure/machine-learning/service/) is still in preview, but I think it could be supported eventually by Luminoth.
