### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by AshwinAce** [tryolabs/luminoth#228]
I have installed Luminoth. I am  able to download checkpoints as well. When i run lumi predict on an image or lumi web server, I get the following error:

`Traceback (most recent call last):`
  `File "/home/ace/anaconda3/bin/lumi", line 11, in <module>
    load_entry_point('luminoth', 'console_scripts', 'lumi')()`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)`
  `File "/home/ace/luminoth/luminoth/predict.py", line 241, in predict
    config = get_checkpoint_config('accurate')`
  `File "/home/ace/luminoth/luminoth/tools/checkpoint/__init__.py", line 210, in get_checkpoint_config
    config = get_config(os.path.join(path, 'config.yml'))`
  `File "/home/ace/luminoth/luminoth/utils/config.py", line 19, in get_config
    model_base_config, custom_config, override_params`
  `File "/home/ace/luminoth/luminoth/utils/config.py", line 225, in get_model_config
    return cleanup_config(config)`
  `File "/home/ace/luminoth/luminoth/utils/config.py", line 204, in cleanup_config
    config.pop(cleanup_key, None)`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/easydict/__init__.py", line 142, in pop
    delattr(self, k)`
`AttributeError: _replace`

For the rest of the getting started section, the code runs with  the following warnings:
`/home/ace/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ace/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)`

From what I understand, the warnings may not necessarily be a problem. Based on the traceback of the error, the indication is that running the lumi script in the bin folder is causing the error. Have I made some mistakes during installation?

**Comment by AshwinAce** [comment]
https://github.com/tryolabs/luminoth/issues/223

This helped. I still have a doubt about whether the warnings might cause future problems.

**Comment by dekked** [comment]
Hi @AshwinAce,

You don't need to worry about the warnings, they are regular TF stuff.

The `_replace` issue looks to be because of change (bug?) introduced in a dependency (easydict).


I close this issue and we can continue the discussion in #223.
