### ISSUE TITLE
tensorflow-probability requirement for sonnet.

### ISSUE THREAD

**Issue by AshwinAce** [tryolabs/luminoth#230]
While installing Luminoth, I had to install tensorflow-probability for running the code. When I try running luminoth on Google cloud, I get the following error.

SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu`

Is there a way to install tensorflow-probability and its GPU equivalent when run on the cloud?

**Comment by dekked** [comment]
Try with the latest version of Luminoth, released yesterday :)

Let me know if you have any issues!
