### ISSUE TITLE
File not found error on the cloud

### ISSUE THREAD

**Issue by AshwinAce** [tryolabs/luminoth#231]
I installed Luminoth by cloning the directory. Luminoth works well locally when run. However it gives
errors when run on the cloud.
`File "/home/ace/anaconda3/lib/python3.6/site-packages/luminoth-0.2.2.dev0-py3.6.egg/luminoth/tools/cloud/gcloud.py", line 241, in train`
    `package_path = build_package(bucket, base_path)`
  `File "/home/ace/anaconda3/lib/python3.6/site-packages/luminoth-0.2.2.dev0-py3.6.egg/luminoth/tools/cloud/gcloud.py", line 100, in build_package`
    `tarball_filename = os.listdir(output_dir)[0]`
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzkr4l45i/output'`

I tried installing by pip but that installed an older version of Luminoth that had an error with 'format' being wrongly written as 'formata'. On retrying to run on the cloud, the same erros with slightly different names occurs.
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpza5fipff/output'`

**Comment by AshwinAce** [comment]
I commented the stdout and stderr statements. The error that comes from all three subprocesses is
`Building custom Luminoth package from "/home/ace/anaconda3/lib/python3.6/site-packages/luminoth-0.2.2.dev0-py3.6.egg".
python: can't open file 'setup.py': [Errno 2] No such file or directory`

When I move setup.py to the required folder, this is the error I get
`FileNotFoundError: [Errno 2] No such file or directory: '/home/ace/anaconda3/lib/python3.6/site-packages/luminoth-0.2.2.dev0-py3.6.egg/README.md'`

On moving README to the  same folder, it submits to the cloud. It runs and then fails after that, I shall submit the same as a new issue.

**Comment by dekked** [comment]
Ok, this helps. Might be related to the workings of Anaconda, which we have never tested with Luminoth, but looks to be quite popular in our user base.

What operating system and Anaconda version do you use?

**Comment by AshwinAce** [comment]
conda version : 4.5.11
conda-build version : 3.10.5
python version : 3.6.5.final.0

I use an Ubuntu 16.04.4.LTS.

**Comment by AshwinAce** [comment]
I have some doubts regarding Luminoth. I'm not sure if they qualify for or even merit the creation of a new issues. All of them are unrelated, and not bugs. If you fell they merit one, I shall delete this and post as a new issue.

The first is whether the training on the computer can be done in a similar fashion to that on the cloud, with the possibility of stopping and resuming from checkpoints.

The second is a question about the faster RCNN itself. The default files have 1000 epochs. How many epochs would be necessary for decent accuracy? In my case, the dataset I use has 70k training examples which might make it unfeasible for running that many epochs. I was wondering if using something like 10 epochs would be enough.

The last question is about whether training can be started from the SSD or Faster RCNN checkpoints. i.e. whether transfer learning can be done by using them as the starting point.

**Comment by dekked** [comment]
> conda version : 4.5.11
> conda-build version : 3.10.5
> python version : 3.6.5.final.0
> 
> I use an Ubuntu 16.04.4.LTS.

Thanks, this is very useful. We'll try to reproduce!

Please create a new issue with the other questions.

**Comment by dekked** [comment]
@AshwinAce Try with latest version (0.2.2) and let us know.
