### ISSUE TITLE
[train] WARNING:tensorflow:Function draw_object_prediction failed with KeyError. Key value: 'classification_prediction'

### ISSUE THREAD

**Issue by JuanSeBestia** [tryolabs/luminoth#235]
The warning appears whenever the checkpoint is saved.

`WARNING:tensorflow:Function draw_object_prediction failed with KeyError. Key value: 'classification_prediction'`

I have not taken care because it does not affect the result or I think so

Mybe you need my config
[config_ssd_colab_201811 (copy).txt](https://github.com/tryolabs/luminoth/files/2553652/config_ssd_colab_201811.copy.txt)

**Comment by nagitsu** [comment]
It's a bug with the SSD Tensoroard image visualization, will look into it.

If you want to avoid the error for now, you can either turn `debug` mode on (which will log all the debugging images for SSD on Tensorboard) or disable image visualization by emptying the `image_vis` field in the config.

**Comment by dekked** [comment]
Fixed in v0.2.2.
