### ISSUE TITLE
Installing the correct version

### ISSUE THREAD

**Issue by AshwinAce** [tryolabs/luminoth#238]
I already had pip installed as before. I cloned the repository, moved to the luminoth folder and then ran
`pip install .[gcloud]`. I have elided results which are repetitions.
```
Processing /home/ace/luminoth
Requirement already satisfied: setuptools>=34.0.0 in /home/ace/anaconda3/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=0.1.1->google-cloud-storage>=1.2.0->luminoth==0.2.3.dev0) (39.1.0)
Requirement already satisfied: protobuf>=3.4.0 in /home/ace/anaconda3/lib/python3.6/site-packages (from google-api-core<2.0.0dev,>=0.1.1->google-cloud-storage>=1.2.0->luminoth==0.2.3.dev0) (3.6.1)
Building wheels for collected packages: luminoth
  Running setup.py bdist_wheel for luminoth ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-q6gp4mtb/wheels/fb/87/5c/9b5a1f2e348d132e9a12ee0e7618a96012e55627dc71be1987
Successfully built luminoth
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: luminoth
  Found existing installation: luminoth 0.2.2
    Uninstalling luminoth-0.2.2:
      Successfully uninstalled luminoth-0.2.2
Successfully installed luminoth-0.2.3.dev0
```
When I try to run on the cloud, this is the error that turns up. Is there a way to guarantee that I install the correct version (0.2.2 in this case)?

```
2018-11-08T21:20:39.313121080Z :: ERROR   :: Could not find a version that satisfies the requirement luminoth==0.2.3dev0 (from luminoth-gcp-setup==0.2.3.dev0) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2)
2018-11-08T21:20:39.315418958Z :: ERROR   :: No matching distribution found for luminoth==0.2.3dev0 (from luminoth-gcp-setup==0.2.3.dev0)
```
Link to logs :https://console.cloud.google.com/logs/viewer?project=frcnn-test0&resource=ml_job%2Fjob_id%2Ftrain_20181108_161702&minLogLevel=0&expandAll=false&timestamp=2018-11-08T21:27:39.740000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22train_20181108_161702%22&dateRangeStart=2018-11-08T20:27:40.944Z&dateRangeEnd=2018-11-08T21:27:40.944Z&interval=PT1H&scrollTimestamp=2018-11-08T21:26:42.099672911Z

**Comment by dekked** [comment]
This is normal. What matters is that the code that build the package now works, so Luminoth will work for you on the cloud.

It will fix itself when we release v0.2.3.

In the meantime, you can install in editable mode: `pip install -e .[gcloud` and it should not give this same error in the cloud.

Thanks for all your help debugging this!
