### ISSUE TITLE
Error while training (using frcnn) on new data set

### ISSUE THREAD

**Issue by annusrcm** [tryolabs/luminoth#245]
I used frcnn algo to detect table in document images. It finished and worked well on UNLV dataset, however when i use the new data set it runs for few images and then gives the following error 

Traceback (most recent call last):
  File "/iq_storage/virtualenv/table_detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/iq_storage/virtualenv/table_detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/iq_storage/virtualenv/table_detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: losses/RPNLoss/background_cls_loss_1
	 [[Node: losses/RPNLoss/background_cls_loss_1 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](losses/RPNLoss/background_cls_loss_1/tag, losses/RPNLoss/boolean_mask_5/GatherV2)]]

Note :  Using the sample code in this [blog](https://blog.goodaudience.com/table-detection-using-deep-learning-7182918d778)

**Comment by annusrcm** [comment]
Hi @nagitsu 

![folder5_training_fail](https://user-images.githubusercontent.com/34880060/48659321-22293800-ea75-11e8-8588-e4667c429ef6.png)
The loss values are very very large, check for step 26, 27, 28 in the image attached.

The contents of the config.yml :

train:
  # Name used to identify the run. Data inside `job_dir` will be stored under
  # `run_name`.
  run_name: table-area-detection-0.1
  # Base directory in which model checkpoints & summaries (for Tensorboard) will
  # be saved.
  job_dir: /iq_storage/table_detection/uq_data/all_uq_tables/5/jobs/
  save_checkpoint_secs: 10
  save_summaries_secs: 10

  # Number of epochs (complete dataset batches) to run.
  num_epochs: 1

dataset:
  type: object_detection
  # From which directory to read the dataset.
  dir:  /iq_storage/table_detection/uq_data/all_uq_tables/5/tfdata/
  image_preprocessing:
    min_size: 600
    max_size: 1024
  data_augmentation:
    - flip:
        left_right: True
        up_down: True
        prob: 0.5

model:
  type: fasterrcnn
  network:
    # Total number of classes to predict.
    num_classes: 1

**Comment by nagitsu** [comment]
The learning rate's definitely too high, try reducing it a bit and check if it stops exploding. You can read more on how to do this [in the tutorial from the docs](https://luminoth.readthedocs.io/en/latest/tutorial/03-training-the-model.html#building-the-config-file-for-your-dataset).

Let me know how it goes :)

**Comment by annusrcm** [comment]
Hi @nagitsu 
I ran the training (everything remaining same) to reproduce the error of having very large training loss but this time the loss is not exploding, in the first epoch the training reached upto some 500 steps and its still below 10. In my config file I have not defined any learning rate so I am assuming the library is using  the default learning rate of 0.0003 as defined in base_config.yml. I am expecting it to explode in some time.

Now I have reduced the learning rate to 0.0001 with exponential decay and will update about it as the training finishes.

**Comment by annusrcm** [comment]
Hi @nagitsu 
With the following configurations for learning rate:
    decay_method: exponential_decay
    decay_rate: 0.5
    decay_steps: 5000
    learning_rate: 0.0003
The problem of exploding RPN loss vanished, however I am getting other error:
**Reduction axis 0 is empty in shape [0,2]**
Shall I raise another issue or post the full error traceback here ?

**Comment by nagitsu** [comment]
The error seems unrelated, please open a new issue with the full traceback :)

By the way, you might want to try a less abrupt decay, such as this:

```
learning_rate:
  decay_method: piecewise_constant
  boundaries: [250000, 450000, 600000]
  values: [0.0003, 0.0001, 0.00003, 0.00001]
```

The boundaries themselves would be different, depending on when the loss stabilizes (you can look at the Tensorboard charts for the losses).
