### ISSUE TITLE
How to adapte a dataset which use Microsoft/VoTT  to export

### ISSUE THREAD

**Issue by gongeek** [tryolabs/luminoth#251]
When I use [Microsoft/VoTT](https://github.com/Microsoft/VoTT)  to create my own dataset. 

First I try export as TF Record . And then use `lumi dataset merge` to get one file . It can't be use in luminoth . It throw  a error when train `tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'depth' is required but could not be found`
![image](https://user-images.githubusercontent.com/3911824/49511712-db39a000-f8c6-11e8-8fc2-9f70a854f438.png)

Then I try export as  Tensorflow Pascal Voc format .And then use `lumi dataset transform 
        --type pascal ...` to transform it to `.tfrecords` format . But it throw Error don't find train.txt 

![image](https://user-images.githubusercontent.com/3911824/49511979-95310c00-f8c7-11e8-8535-76c71f510814.png)

How to adapte a dataset which use Microsoft/VoTT  to export? Or Which Visual Object Tagging Tool you suggest to use ?

**Comment by sleipniry** [comment]
I have the same problem.Have you solved it?

**Comment by gongeek** [comment]
@sleipniry 
You can parse the `img.json` which Microsoft/VoTT exported to  `train.csv` format .
the format is like this 
![image](https://user-images.githubusercontent.com/3911824/49913432-87334a80-fec8-11e8-9c77-1c1b63009137.png)

https://github.com/tryolabs/luminoth/blob/master/luminoth/tools/dataset/readers/object_detection/csv_reader.py
