### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by nagitsu** [tryolabs/luminoth#27]
- [x] Installation instructions
- [ ] Usage instructions
- [ ] Testing instructions
- [ ] High-level description & better name explanation
- [ ] Using your own dataset (explanation of .tfrecords format)

**Comment by mjmare** [comment]
I concur. Though experienced in python, I, without experience in AI+CV, do not know what to do after installing luminoth. Some basic and more complex examples without training would be useful to get a taste of Luminoth.

**Comment by vierja** [comment]
@mjmare we are working on it. You should except some updates on this over the next couple of weeks.

**Comment by mjmare** [comment]
Great! Looking forward to it. Thx.
