### ISSUE TITLE
Is a TF2.0 compatible version planned?

### ISSUE THREAD

**Issue by mannykoum** [tryolabs/luminoth#284]
My team is moving to tensorflow 2.0 and I was wondering if luminoth will be supporting it in the near future.

**Comment by mannykoum** [comment]
there is also a number of deprecation warnings

**Comment by joaqo** [comment]
Hey! We are evaluating the state of TF2 at the moment, and planning how a migration to it would be. Will get back to you when we have more details.

**Comment by wlwg** [comment]
Any news about this please?

**Comment by dekked** [comment]
Hello,

We are currently working on Luminoth v2, but we have decided to move to PyTorch instead, leveraging the torch vision ecosystem.
This version will have all the good things about Luminoth, but it will be much more accurate, faster to train, and the recent advances in vision will be easier to integrate.

Best,
Alan
