### ISSUE TITLE
predict is taking 16sec on CPU. 

### ISSUE THREAD

**Issue by interviewBubble** [tryolabs/luminoth#292]
LUMINOTH is taking 16sec to give output. is it expected or i am giving more.

if it is expected then how can i result in milliseconds?

**Comment by dekked** [comment]
Hi @interviewBubble. This is normal if you are using a CPU for inference.

For a faster model, try SSD. But for milliseconds, you are going to need a GPU.

**Comment by interviewBubble** [comment]
I have this requirement: I have to process more than 300 pages within a second.
What should I do?
can you give me some advice? Because it can not be deployed on the server

**Comment by dekked** [comment]
Unfortunately, there is no model in Luminoth suitable for this requirement.

You might want to look into lightweight variants of the SSD model, but you will need at least one GPU for this speed.
