### ISSUE TITLE
Local Checkpoint not being detected

### ISSUE THREAD

**Issue by anantnd** [tryolabs/luminoth#299]
Running the 'lumi checkpoint refresh/list' on my local dir where the checkpoint is stored, yet the checkpoint is not being detected.

**Comment by anantnd** [comment]
The last time I did that (a month ago) it had worked fine. Today it just showed the remote checkpoints

**Comment by dekked** [comment]
Hi @anantnd. Luminoth is no longer maintained. We recommend switching to [Detectron2](https://github.com/facebookresearch/detectron2) instead.
