### ISSUE TITLE
Hitting a problem as soon as I run lumi

### ISSUE THREAD

**Issue by mbhoshen** [tryolabs/luminoth#303]
(luminoth) C:\Users\moshe\luminoth>lumi checkpoint refresh
Luminoth requires a TensorFlow >= 1.5 installation.

Depending on your use case, you should install either `tensorflow` or
`tensorflow-gpu` packages manually or via PyPI.

I installed specially tensorflow 1.5, to get is as simple as possible (not GPU, though with a GPU and tensorflow-gpu I got the same) 
python 3.6
Windows 10
and then pip install luminoth
running lumi --help, or any other lumi command I get this error

in a special conda environment
in a python shell I can import tensorflow
Any ideas what might be wrong?

Thanks!!

**Comment by AlphonsG** [comment]
So other lumi commands work, only `lumi checkpoint refresh` doesnt?

**Comment by mbhoshen** [comment]
Thanks
Any lumi command raises the error. 
It just does not see the package, even though within the environment, python does see it. I was trying to run luminoth as a basis for Tabulo, and that is where I started seeing the problem. I found that I was hitting an exception being raised on the tensorflow issue. It seems to happen within lumi.exe, not within python, so I can't fix the code, but it must be something to do with the installation, where something must be wrong.
I am really looking for a good program to detect tables and their structure, and this looked just great, but I am hitting a brick wall.
Any help would be much appreciated

**Comment by AlphonsG** [comment]
Okay, try a new environment and install luminoth with tensorflow 1.15. If that doesn't work, create another environment and try `pip install luminoth[tf] or pip install luminoth[tf-gpu]` as the Readme says.

Btw, I would use this repo https://github.com/open-mmlab/mmdetection instead of this one now. Luminoth is nice, but it's no longer supported while mmdetection should be better in every single way.

**Comment by IanTayler** [comment]
> Okay, try a new environment and install luminoth with tensorflow 1.15. If that doesn't work, create another environment and try `pip install luminoth[tf] or pip install luminoth[tf-gpu]` as the Readme says.
> 
> Btw, I would use this repo https://github.com/open-mmlab/mmdetection instead of this one now. Luminoth is nice, but it's no longer supported while mmdetection should be better in every single way.

Agreed.

Facebook's [Detectron 2](https://github.com/facebookresearch/detectron2) is another good option.

Luminoth is not going to be mantained in the future so if you're starting a new project I'd recommend against using Luminoth.

**Comment by mbhoshen** [comment]
> > Okay, try a new environment and install luminoth with tensorflow 1.15. If that doesn't work, create another environment and try `pip install luminoth[tf] or pip install luminoth[tf-gpu]` as the Readme says.
> > Btw, I would use this repo https://github.com/open-mmlab/mmdetection instead of this one now. Luminoth is nice, but it's no longer supported while mmdetection should be better in every single way.
> 
> Agreed.
> 
> Facebook's [Detectron 2](https://github.com/facebookresearch/detectron2) is another good option.
> 
> Luminoth is not going to be mantained in the future so if you're starting a new project I'd recommend against using Luminoth.

Thanks https://github.com/AIanTaylor and https://github.com/AlphonsGwatimba did try that option of installing a new venv and  pip install luminoth[tf-gpu] but it ended up the same way
So I will have to just move on, perhaps with detectron2, though that means developing in Linux, when my organisation is all Windows, but that is where the knowledge is ..
Thanks!
