### ISSUE TITLE
Performance issues in the programs

### ISSUE THREAD

**Issue by DLPerf** [tryolabs/luminoth#308]
Hello, I found a performance issue in the definition of `_build`, luminoth/models/ssd/proposal.py, [tf.shape](https://github.com/tryolabs/luminoth/blob/9109d8b98bcbb0ad4e8e0c928da0b20627fa774f/luminoth/models/ssd/proposal.py#L104) will be calculated repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop in `_build`.

The same issue exists in [tf.cast](https://github.com/tryolabs/luminoth/blob/9109d8b98bcbb0ad4e8e0c928da0b20627fa774f/luminoth/models/ssd/proposal.py#L113)

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by AlphonsG** [comment]
Hello, this repo is no longer supported sadly. Thanks.
