### ISSUE TITLE
Your website is exceptionally unreadable because of poor font color choices.

### ISSUE THREAD

**Issue by fiendish** [tryolabs/luminoth#88]
![screenshot from 2017-10-12 14-47-28](https://user-images.githubusercontent.com/201996/31513544-a9a61b0e-af5c-11e7-8a23-0d4d30376dd1.png)

Contrast, please. ^_^

**Comment by mfagioli** [comment]
Hi @fiendish, thanks for detecting this. We'll fix it in our next deploy. Cheers!
